services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      QDRANT_API_KEY: "${QDRANT_API_KEY}"
    volumes:
      - "${QDRANT_STORAGE}:/qdrant/storage"
      - "${SSL_CERTS_PATH}:/qdrant/tls"
      - "./qdrant_server_config.yaml:/qdrant/config/config.yaml"
    command: ["./qdrant", "--config-path", "/qdrant/config/config.yaml"]
